import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './style.css'

const inter = Inter({ subsets: ['latin'] })

export const runtime = 'edge'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(ps: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>{ps.children}</body>
    </html>
  )
}
